- src/css/main.css
http://www.outlinenone.com/
> What does the outline property do?
> 
> It provides visual feedback for links that have "focus" when navigating a web document using the TAB key (or equivalent). This is especially useful for folks who can't use a mouse or have a visual impairment. If you remove the outline you are making your site inaccessible for these people.
> 
> Defining focus to navigation elements is an accessibility requirement, it's clearly stated in the Web Content Accessibility Guidelines:
> 
> 2.4.7 Focus Visible: Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible. (Level AA)
>
> Remove outline: none

- index.html
- src/css/notifications.css
Added an unboxed notification taking the full width of its container. Aimed for more general notifications.
Also added a class for closable notifications that adds a padding as the close button was passing over text.
Will be used on entreprise.data.gouv.fr:
> Add full width notice

- index.html
- src/css/button.css
- src/css/form.css
- src/css/main.css
- src/css/panel.css
- src/css/theme.css
New panel layout needed for api-administration, added here for reuse and example.
Also removed the box-shadow on buttons to make them cleaner and the icon-rss declaration that was here twice.
> Add a panel layout for api-administration

- index.html
- src/css/documentation.css
- src/css/index.css
- src/css/markdown.css
- src/css/typography.css
Documentation didn't render properly so a few adjustments have been made.
- Made the side pane and content width proportional
- Added the markdown specific style from doc.data.gouv.fr
> Adjust documentation layout

- src/css/nav.css
2 raisons :
- le gris plus clair est moins "triste" (AMHA)
- on a un plus fort contraste entre la couleur de fond et la couleur du texte
> Change the nav link hover color to lighter grey

- src/css/button.css
- src/css/form.css
Suppression des bordures pointillées qui apparaissent sur les `select` et les `button` au focus
> Remove the Firerfox focus rings

- src/css/grid.css
Dans un `row`, aligner verticalement les éléments "en haut" et pas "au milieu"
Avant :
Après :
> Vertically align row items to the top, instead of the center

- src/css/button.css
Je trouve qu'utiliser le caractère de corps pour les boutons est plus naturel que d'utiliser celui de titrage.
Avant :
Après :
> Use Source Sans Pro instead of Evolventa for buttons

- src/css/documentation.css
- Comme pour #39, je trouve que c'est trop lent, qu'on attend, que ça lag
- Ça permet d'unifier le comportement au hover de tous les éléments du `side-pane` : les éléments de niveau 0 n'ont pas de transition au hover, par contre ceux de niveau 1 (qui font parti du `submenu`) en ont une, ce qui est bizarre à mes yeux
> Remove transitions in the side menus

- package.json
Since I moved icons from their original directory, npm script wasn't copying them anymore.
Changed the script to take the new directory into account.
Fixes #63
> Fix icons copy

- package.json
`yarn dist` builds and `yarn deploy` deploys.
The build output is generated in the `build` CI task, saved to workspace, and deployed using `yarn deploy` in the `deploy` CI task.
If deploying from your local machine, you will need to run both commands though. Though the deployment seems automated by Circle CI. :)
> Stop building twice on CI

- index.html
This pull request fixes a small typo where some hexa colors codes (starting with `#`) displayed on the page wouldn't match the actual color attached to them. Also, the pull request removes caps from hexa codes to improve readability.
> Fix the mismatch between hexa color codes and actual colors

- src/css/layouts/footer.css
- src/css/layouts/section.css
Links on hover with a dark background were unreadable because of light background change.
Changed to a darker color for better readability.
Fix #91
> fix links in footer

- CHANGELOG.md
- index.html
- src/css/elements/input.css
Labels can have a `required` class that adds a red ✽ next to them.
Fix #96
> add style for required input labels

- CHANGELOG.md
- index.html
As suggested in #70, there's now a link to a polyfill for Internet Explorer that doesn't handle grids.
> add a polyfill for IE

- CHANGELOG.md
- src/css/elements/input.css
- Fix the visual glitch on select #95 
- Use padding in `em` on inputs so they resize with font-size
_new looks in Chrome_
> fix and improvements: inputs

- src/css/components/panel.css
- src/css/template.css
- src/css/utility/layout.css
According to feedbacks, panels should be separated by margins when they follow each other.
This should give all following panels margins according to the layout they're in.
> set margin to panels by default

- CHANGELOG.md
- src/css/elements/button.css
- src/css/elements/input.css
- Added a new color to buttons
- `input[type="submit"]` now has the same default width and a pointer on hover
- Checkboxes and radio buttons options now have a larger margins between them
- Selects on Firefox are the same height as other inputs
- Required marker is now set on the left of labels for better scanning
> inputs enhancements

- src/css/components/form.css
- src/css/elements/button.css
Make buttons take full width on mobile and add a margin on top of following buttons.
> improve buttons for responsive

- CHANGELOG.md
- README.md
- index.html
- package.json
- src/css/base/theme.css
- src/css/components/pagination.css
- src/css/elements/table.css
- src/css/index.css
- added a style for pagination
- added a style for sorting and filtering
Closes #112
> add utilities to tables

- src/css/elements/button.css
When a button has the focus it was dark-blue or white for button-outlined. 
This PR fixes this and keep the button in dark-red for warning, ...
> Fix the color of a button when it has the :focus.

- src/css/components/form.css
- src/css/elements/input.css
- src/css/elements/switch.css
For some reason flexbox doesn't work on the fieldset on chrome anymore so it has been removed.
I also realigned the inputs while at it.
> fix input inlining on chrome

- src/css/components/pagination.css
I got warning from a linter with the current `end` value.
This should render the same thing.
cf:
https://caniuse.com/#search=justify-content
> Use most supported flex-end for justify-content in pagination
