index.html
src/css/dropdown.css
src/css/index.css

Ajout de la sélection de la langue

---

src/css/template.css

Moved template.css to `src/css` folder so it can be used by postcss.

Moved template.css to `src/css` folder

---

index.html
src/css/code.css
src/css/documentation.css
src/css/index.css
src/css/main.css
src/css/nav.css
src/css/template.css

add two-panes documentation style

---

index.html
src/css/article.css
src/css/footer.css
src/css/form.css
src/css/index.css
src/css/nav.css

Ajout article

---

src/css/code.css
src/css/container.css
src/css/documentation.css
src/css/grid.css
src/css/index.css
src/css/media-queries.css
src/css/nav.css
src/css/template.css

Plus quelques détails sur l'affichage "responsive"

Ajout de custom media queries

---

index.html
src/css/form.css

https://www.w3.org/WAI/tutorials/forms/grouping/

Bonne pratique a11y

---

index.html
src/css/dropdown.css
src/css/footer.css
src/css/hero.css
src/css/main.css
src/css/nav.css
src/css/template.css
src/css/theme.css

Petits fixes de marges et de couleurs (entre autres).

améliorations diverses

---

index.html
src/css/button.css
src/css/container.css
src/css/footer.css
src/css/grid.css
src/css/nav.css
src/css/typography.css

Made some changes for things that weren't working well on entreprise.api.gouv.fr new homepage.
- Fixed buttons animation
- Added classes for columns and alignment
- Added a link to the logo in the header

Improvements from entreprise.api.gouv.fr

---

index.html

J'ai effectué l'audit d'accessibilité de chrome et corrigé les quelques erreurs trouvées:
- https://dequeuniversity.com/rules/axe/2.2/duplicate-id?application=lighthouse
- https://dequeuniversity.com/rules/axe/2.2/color-contrast?application=lighthouse
- https://dequeuniversity.com/rules/axe/2.2/label?application=lighthouse
- https://dequeuniversity.com/rules/axe/2.2/link-name?application=lighthouse
- https://dequeuniversity.com/rules/axe/2.2/image-alt?application=lighthouse
- https://dequeuniversity.com/rules/axe/2.2/button-name?application=lighthouse
(Je trouve d'ailleurs ce site très bien pour expliquer le problème et les pistes de résolutions)

A11y audit

---

index.html

Suppression de toutes les [erreurs relevées par le validateur W3C](https://validator.w3.org/nu/?doc=https%3A%2F%2Fetalab.github.io%2Ftemplate.data.gouv.fr%2F)

W3C validation

---

src/css/grid.css

Add spacing below columns on smaller than tablet widths

---

src/css/form.css

Add focus to textarea

---

index.html
src/css/typography.css

Je l'ai ajouté dans la partie "Typographie", je ne sais pas si c'est le bon endroit.
Tout en bas ici:

Ajout d'affichage de citations

---

index.html
src/css/dashboard.css
src/css/index.css
src/css/main.css
src/css/panel.css
src/css/table.css
src/css/template.css

Add style for dashboard as documentation wasn't exactly appropriate for a dashboard layout.
Things we could add to this:
* icons for navigation
* button to toggle navigation

add style for table and dashboard

---

index.html
src/css/table.css
src/css/theme.css

Added a lighter shade of grey (🤷‍♀️) for table row hover that was initially the same as the thead color and fixed table content.

improve table

---

package.json
src/css/footer.css
src/css/hero.css
src/css/nav.css

There were inconsistencies when using template on beta.gouv.fr, this fixes:
- responsive on header and footer
- wrong color in hero title
Also did I forget to push `package.json` modifications? 🤔

fix quirks noticed when reworking beta.gouv.fr homepage

---

src/css/hero.css

Title was white on white.
Messed up my classes, sorry. -_-

fix hero title

---

index.html
src/css/sections.css
src/css/table.css

put style of tables and sections in a class

---

index.html
package.json
src/css/button.css
src/css/template.css

Add a lighter button style, works better on colored backgrounds.

Add outlined button

---

index.html
package.json
src/css/footer.css
src/css/grid.css
src/css/labels.css
src/css/nav.css
src/css/panel.css
src/css/table.css
src/css/theme.css

Add small improvements:
- Fix some typos
- Fix the stretched footer logo 
- Increase column margin and remove unused classes
- Remove underline on link labels
- Adjust logo height
- Improve readability

Ui improvements

---

package.json

This PR modifies the way images are copied to dist directory, as subdirectories were not taken into account.

fix directory copy

---

index.html
src/css/base/theme.css
src/css/components/card.css
src/css/components/dropdown.css
src/css/components/form.css
src/css/components/modal.css
src/css/components/notification.css
src/css/components/panel.css
src/css/elements/button.css
src/css/elements/table.css
src/css/layouts/article.css
src/css/layouts/container.css
src/css/layouts/dashboard.css
src/css/layouts/documentation.css
src/css/layouts/footer.css
src/css/layouts/hero.css
src/css/layouts/nav.css
src/css/layouts/section.css
src/css/template.css
src/css/utility/layout.css

Current spacing felt a bit awkward, being too large sometimes.
I created variables for common spacing and changed padding mostly.

use variables for spacing and adjust for smoother spacing

---

index.html
src/css/base/theme.css
src/css/elements/button.css

Top : hover/active
Botton : normal

Add button warning-orange

---

index.html
src/css/components/form.css

This should resolve #107 : 
* better checkbox/radio - label alignment
* better wrapping of labels with long text
* better vertical centering of overlay icons in input

Elements alignment

---

index.html
src/css/layouts/hero.css
src/css/layouts/nav.css
src/css/template.css

Removed the gradient and the blue background to make it white for a cleaner look.

make hero white by default

---

CHANGELOG.md
index.html
src/css/base/theme.css
src/css/layouts/article.css
src/css/layouts/footer.css
src/css/layouts/section.css
src/css/template.css

- Added a darker tone of blue
- Changed light red to a lighter tone, for consistency with other light tones
- Changed blue background to gradient blue

color enhancement

---

index.html

https://fr.wikipedia.org/wiki/All_your_base_are_belong_to_us

Fix typo AYBABTU

---

README.md

from 1.1.6 to 1.2.2 import path changed

update readme for new import path

---

index.html
src/css/elements/switch.css
src/css/index.css

This PR adds 2 type switches to checkbox styles : 
* simple switch like for option activation/desactivation
* switch with text to choose between 2 propositions

Add Switches

---

src/css/elements/button.css

Fix proposal for #103 on buttons margins.

---

index.html
src/css/components/steps-form.css
src/css/index.css

Adds a new component to add steps to form

Adds steps form component

---

src/css/elements/input.css

Aligns text and button of file input
